export const STATE_FACTS = {
  alabama: {
    depositCap:     'No statutory cap',
    returnTimeline: '35 days',
    noticeToEnter:  '48 hours',
    lateFee:        'No statutory cap',
  },
  alaska: {
    depositCap:     '2 months rent',
    returnTimeline: '14 days (no deductions) / 30 days (with deductions)',
    noticeToEnter:  '24 hours',
    lateFee:        'No statutory cap',
  },
  arizona: {
    depositCap:     '1.5 months rent',
    returnTimeline: '14 days',
    noticeToEnter:  '48 hours (2 days)',
    lateFee:        'No statutory cap',
  },
  arkansas: {
    depositCap:     'No statutory cap',
    returnTimeline: '60 days',
    noticeToEnter:  'No statute',
    lateFee:        'No statutory cap',
  },
  california: {
    depositCap:     '1 month rent (unfurnished)',
    returnTimeline: '21 days',
    noticeToEnter:  '24 hours',
    lateFee:        'Must be reasonable',
  },
  colorado: {
    depositCap:     'No statutory cap',
    returnTimeline: '30 days',
    noticeToEnter:  '24 hours',
    lateFee:        'No statutory cap',
  },
  connecticut: {
    depositCap:     '2 months rent',
    returnTimeline: '30 days',
    noticeToEnter:  'Reasonable notice',
    lateFee:        '$5/day or 5% of rent',
  },
  delaware: {
    depositCap:     '1 month rent',
    returnTimeline: '20 days',
    noticeToEnter:  '48 hours (2 days)',
    lateFee:        '5% of rent',
  },
  florida: {
    depositCap:     'No statutory cap',
    returnTimeline: '15 days (no deductions) / 30 days (with deductions)',
    noticeToEnter:  '12 hours',
    lateFee:        'No statutory cap',
  },
  georgia: {
    depositCap:     'No statutory cap',
    returnTimeline: '30 days',
    noticeToEnter:  'No statute',
    lateFee:        'No statutory cap',
  },
  hawaii: {
    depositCap:     '1 month rent',
    returnTimeline: '14 days',
    noticeToEnter:  '24 hours',
    lateFee:        'No statutory cap',
  },
  idaho: {
    depositCap:     'No statutory cap',
    returnTimeline: '21 days',
    noticeToEnter:  'No statute',
    lateFee:        'No statutory cap',
  },
  illinois: {
    depositCap:     'No statutory cap (Chicago: no cap)',
    returnTimeline: '30 days',
    noticeToEnter:  'No statute statewide',
    lateFee:        'No statutory cap',
  },
  indiana: {
    depositCap:     'No statutory cap',
    returnTimeline: '45 days',
    noticeToEnter:  'No statute',
    lateFee:        'No statutory cap',
  },
  iowa: {
    depositCap:     '2 months rent',
    returnTimeline: '30 days',
    noticeToEnter:  '24 hours',
    lateFee:        'No statutory cap',
  },
  kansas: {
    depositCap:     '1 month rent (unfurnished) / 1.5 months (furnished)',
    returnTimeline: '30 days',
    noticeToEnter:  'Reasonable notice',
    lateFee:        'No statutory cap',
  },
  kentucky: {
    depositCap:     'No statutory cap',
    returnTimeline: '30 days',
    noticeToEnter:  '24 hours',
    lateFee:        'No statutory cap',
  },
  louisiana: {
    depositCap:     'No statutory cap',
    returnTimeline: '30 days',
    noticeToEnter:  'No statute',
    lateFee:        'No statutory cap',
  },
  maine: {
    depositCap:     '2 months rent',
    returnTimeline: '30 days',
    noticeToEnter:  '24 hours',
    lateFee:        'No statutory cap',
  },
  maryland: {
    depositCap:     '2 months rent',
    returnTimeline: '45 days',
    noticeToEnter:  'No statute',
    lateFee:        '5% of rent',
  },
  massachusetts: {
    depositCap:     '1 month rent',
    returnTimeline: '30 days',
    noticeToEnter:  'No statute',
    lateFee:        'No statutory cap (30-day grace period)',
  },
  michigan: {
    depositCap:     '1.5 months rent',
    returnTimeline: '30 days',
    noticeToEnter:  'No statute',
    lateFee:        'No statutory cap',
  },
  minnesota: {
    depositCap:     'No statutory cap',
    returnTimeline: '21 days',
    noticeToEnter:  'Reasonable notice',
    lateFee:        '8% of rent',
  },
  mississippi: {
    depositCap:     'No statutory cap',
    returnTimeline: '45 days',
    noticeToEnter:  'No statute',
    lateFee:        'No statutory cap',
  },
  missouri: {
    depositCap:     '2 months rent',
    returnTimeline: '30 days',
    noticeToEnter:  'No statute',
    lateFee:        'No statutory cap',
  },
  montana: {
    depositCap:     'No statutory cap',
    returnTimeline: '30 days',
    noticeToEnter:  '24 hours',
    lateFee:        'No statutory cap',
  },
  nebraska: {
    depositCap:     '1 month rent',
    returnTimeline: '14 days',
    noticeToEnter:  '24 hours',
    lateFee:        'No statutory cap',
  },
  nevada: {
    depositCap:     '3 months rent',
    returnTimeline: '30 days',
    noticeToEnter:  '24 hours',
    lateFee:        'No statutory cap',
  },
  'new-hampshire': {
    depositCap:     '1 month rent or $100 (whichever is greater)',
    returnTimeline: '30 days',
    noticeToEnter:  'No statute',
    lateFee:        'No statutory cap',
  },
  'new-jersey': {
    depositCap:     '1.5 months rent',
    returnTimeline: '30 days',
    noticeToEnter:  'No statute',
    lateFee:        'No statutory cap',
  },
  'new-mexico': {
    depositCap:     '1 month rent (under 1 year) / no cap (over 1 year)',
    returnTimeline: '30 days',
    noticeToEnter:  '24 hours',
    lateFee:        '10% of rent',
  },
  'new-york': {
    depositCap:     '1 month rent',
    returnTimeline: '14 days',
    noticeToEnter:  'No statute',
    lateFee:        '$50 or 5% of rent (whichever is less)',
  },
  'north-carolina': {
    depositCap:     '2 months rent (month-to-month: 1.5 months)',
    returnTimeline: '30 days',
    noticeToEnter:  'No statute',
    lateFee:        '$15 or 5% of rent (whichever is greater)',
  },
  'north-dakota': {
    depositCap:     '1 month rent',
    returnTimeline: '30 days',
    noticeToEnter:  'No statute',
    lateFee:        'No statutory cap',
  },
  ohio: {
    depositCap:     'No statutory cap',
    returnTimeline: '30 days',
    noticeToEnter:  '24 hours',
    lateFee:        'No statutory cap',
  },
  oklahoma: {
    depositCap:     'No statutory cap',
    returnTimeline: '45 days',
    noticeToEnter:  '24 hours',
    lateFee:        'No statutory cap',
  },
  oregon: {
    depositCap:     'No statutory cap',
    returnTimeline: '31 days',
    noticeToEnter:  '24 hours',
    lateFee:        'No statutory cap',
  },
  pennsylvania: {
    depositCap:     '2 months rent (year 1) / 1 month (year 2+)',
    returnTimeline: '30 days',
    noticeToEnter:  'No statute',
    lateFee:        'No statutory cap',
  },
  'rhode-island': {
    depositCap:     '1 month rent',
    returnTimeline: '20 days',
    noticeToEnter:  '24 hours',
    lateFee:        'No statutory cap',
  },
  'south-carolina': {
    depositCap:     'No statutory cap',
    returnTimeline: '30 days',
    noticeToEnter:  '24 hours',
    lateFee:        'No statutory cap',
  },
  'south-dakota': {
    depositCap:     '1 month rent',
    returnTimeline: '14 days (no deductions) / 45 days (with deductions)',
    noticeToEnter:  'No statute',
    lateFee:        'No statutory cap',
  },
  tennessee: {
    depositCap:     'No statutory cap',
    returnTimeline: '30 days',
    noticeToEnter:  '24 hours',
    lateFee:        'No statutory cap',
  },
  texas: {
    depositCap:     'No statutory cap',
    returnTimeline: '30 days',
    noticeToEnter:  'No statute',
    lateFee:        'No statutory cap',
  },
  utah: {
    depositCap:     'No statutory cap',
    returnTimeline: '30 days',
    noticeToEnter:  '24 hours',
    lateFee:        'No statutory cap',
  },
  vermont: {
    depositCap:     'No statutory cap',
    returnTimeline: '14 days',
    noticeToEnter:  '48 hours',
    lateFee:        'No statutory cap',
  },
  virginia: {
    depositCap:     '2 months rent',
    returnTimeline: '45 days',
    noticeToEnter:  '24 hours',
    lateFee:        '10% of monthly rent',
  },
  washington: {
    depositCap:     'No statutory cap',
    returnTimeline: '30 days',
    noticeToEnter:  '48 hours (2 days)',
    lateFee:        'No statutory cap',
  },
  'west-virginia': {
    depositCap:     'No statutory cap',
    returnTimeline: '60 days',
    noticeToEnter:  'No statute',
    lateFee:        'No statutory cap',
  },
  wisconsin: {
    depositCap:     'No statutory cap',
    returnTimeline: '21 days',
    noticeToEnter:  '12 hours',
    lateFee:        'No statutory cap',
  },
  wyoming: {
    depositCap:     'No statutory cap',
    returnTimeline: '30 days',
    noticeToEnter:  'No statute',
    lateFee:        'No statutory cap',
  },
};
